version: '3.7'
services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "cibot"
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
      MYSQL_PASSWORD: ""
    volumes:
      - mysql-data:/var/lib/mysql
  app:
    build:
      context: .
      dockerfile: .docker/Dockerfile
    image: 'laravelapp'
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www/html
    user: '1000:1000'

  composer:
    restart: 'no'
    image: composer:2
    command: install
    volumes:
      - .:/app

  composer:
    restart: 'no'
    image: composer:2
    command: install
    volumes:
      - .:/app

volumes:
  mysql-data: null
